// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChatList: typeof import('./src/components/ChatList.vue')['default']
    ChatMessageList: typeof import('./src/components/ChatMessageList.vue')['default']
    CustToast: typeof import('./src/components/toast/custToast.vue')['default']
    Message: typeof import('./src/components/Message/Message.vue')['default']
    MsgTip: typeof import('./src/components/MsgTip/MsgTip.vue')['default']
    PrivateChat: typeof import('./src/components/PrivateChat.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Send: typeof import('./src/components/Send.vue')['default']
    SendMessage: typeof import('./src/components/SendMessage.vue')['default']
  }
}
